module.exports = {
  apps: [
    {
      name: 'dashmaster-next',
      script: 'node_modules/.bin/next',
      args: 'start',
      cwd: '/home/charles/Code/dashmaster/dashmaster-ui',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PORT: 5000,
      },
      error_file: './logs/next-error.log',
      out_file: './logs/next-out.log',
      log_file: './logs/next-combined.log',
      time: true,
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: 'dashmaster-server',
      script: 'ts-node',
      args: '--project tsconfig.server.json server/index.ts',
      cwd: '/home/charles/Code/dashmaster/dashmaster-ui',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
        PORT: 5001,
      },
      error_file: './logs/server-error.log',
      out_file: './logs/server-out.log',
      log_file: './logs/server-combined.log',
      time: true,
      kill_timeout: 5000,
    },
  ],
};
